package fitbit;

/**
 * Display.java
 * AUTHOR: TEAM HUNGRY
 * CLASS: CSCI 360-01
 * PURPOSE: TO READ FROM DISPLAY READY DATASET
 *      TO DYNAMICALLY DISPLAY THE DATA
 *      TO ENABLE SETTINGS CHANGES
 *  OTHER:
 *      1) CALLS DATAIO ON DISPLAY READY DATASET, DISPLAYS DATA
 *      2) CALLS DATAIO ON SETTINGS DATASET, ALTERS DATA, SUBMITS CHANGES
 *
 *      RDD: CALLS INFORMATION EXPERT
 */
public class Display {
    //TEST THIS SHIT;
}
