package FitBit;

/**
 * FileIO.java
 * AUTHOR: TEAM HUNGRY
 * CLASS: CSCI 360-01
 * PURPOSE: TO TRACK SENSORS AND INTERPRET/STORE DATA IN RAW DATASET
 * OTHER:
 *      1) TRACKS INPUT FROM SENSORS INTO TEMPORARY MEMORY
 *      2) INTERPRETS DATA INTO CALCULATION-FRIENDLY FORMAT
 *              a) INTERPRETS ANALOG ACCELEROMETER DATA INTO INT STEPS
 *              b) INTERPRETS ANALOG HEARTRATE DATA INTO FLOAT BPS
 *      3) CALLS FILEIO TO OUTPUT FINISHED INFO TO RAW DATA
 */
public class SensorData {
}
