package fitbit;

/**
 * SettingsExpert.java
 * AUTHOR: TEAM HUNGRY
 * CLASS: CSCI 360-01
 * PURPOSE: TO GRANT ACCESS TO ALL PERTINENT DISPLAY-READY DATA
 *      1) CLOCK SETTINGS DATASET
 *      2) USER INFORMATION DATASET
 *
 *      WHAT IS PASSED BY THE DATA EXPERT (ELSEWHERE)
 *      1) STEPS AND BPS DATASET
 *      2) CURRENT TIME FROM CLOCK CLASS
 *      3) CALCULATED DATA DATASET (HEARTRATE, ACTIVE RATIO, CALORIES BURNED)
 */

public class SettingsExpert {

}
